version: "3"
services:
  flask-api:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "5000:5000"
    volumes:
      - ./app:/base/app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
