version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    restart: always
    ports:
      - "5050:5000"
    volumes:
      - ./app:/base/app
    environment:
      - GRADIO_PORT=7860
      - LOCALHOST_API_PORT=5055
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "5055:5000"
    volumes:
      - ./backend:/base/backend
  gradio:
    build:
      dockerfile: Dockerfile
      context: ./chat_module
    ports:
      - "7860:7860"
    environment:
      - API_HOST=backend
      - API_PORT=5000
    #depends_on:
    #  # ! does not wait until app is up and running
    #  - app
    #restart: on-failure:3
