version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    ports:
      - "5050:5000"
    volumes:
      - ./app:/base/app
    environment:
      - GRADIO_PORT=7860
      - LOCALHOST_PORT=5050
  gradio:
    build:
      dockerfile: Dockerfile
      context: ./chat_module
    ports:
      - "7860:7860"
    environment:
      - FLASK_HOST=app
      - FLASK_PORT=5000
    depends_on:
      # ! does not wait until app is up and running
      - app
    restart: on-failure:3
